### ISSUE TITLE
no `Alloc` in `alloc`

### ISSUE THREAD

**Issue by haraldh** [phil-opp/linked-list-allocator#19]
```
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling linked_list_allocator v0.6.5
error[E0432]: unresolved import `alloc::alloc::Alloc`
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/linked_list_allocator-0.6.5/src/lib.rs:14:20
   |
14 | use alloc::alloc::{Alloc, AllocErr, Layout};
   |                    ^^^^^
   |                    |
   |                    no `Alloc` in `alloc`
   |                    help: a similar name exists in the module: `alloc`

error: aborting due to previous error
```

**Comment by phil-opp** [comment]
Thanks for reporting! This is caused by https://github.com/rust-lang/rust/pull/68529 and the subsequent https://github.com/rust-lang/rust/pull/68736. I'll push a fix.
