### PR TITLE
Fix build on nightly 1.43.0 (05-03-2020).

### LINKED ISSUE #24: Unable to build on rust version 1.43.0-nightly
I tried to build following code with dependency on `linked-list-allocator` version `0.7.0`:

```rust
use linked_list_allocator::LockedHeap;
```

However I got this error:

```rust
error[E0053]: method `alloc` has an incompatible type for trait
   --> /Users/mac/.cargo/registry/src/github.com-1ecc6299db9ec823/linked_list_allocator-0.7.0/src/lib.rs:133:5
    |
133 |     unsafe fn alloc(&mut self, layout: Layout) -> Result<NonNull<u8>, AllocErr> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected tuple, found struct `core::ptr::NonNull`
    |
    = note: expected fn pointer `unsafe fn(&mut Heap, core::alloc::Layout) -> core::result::Result<(core::ptr::NonNull<u8>, usize), _>`
               found fn pointer `unsafe fn(&mut Heap, core::alloc::Layout) -> core::result::Result<core::ptr::NonNull<u8>, _>`
```

My Rust version is `rustc 1.43.0-nightly (75cf41afb 2020-03-04)`.

### PR DESCRIPTION
**Pull request by Darksecond**
The AllocRef trait has been changed slightly.
See https://doc.rust-lang.org/nightly/std/alloc/trait.AllocRef.html#tymethod.alloc.

Fix #24

### CODE REVIEW

**Comment by phil-opp** [comment]
Thanks a lot!

**Comment by phil-opp** [comment]
In order to avoid issues like https://github.com/phil-opp/linked-list-allocator/issues/21, I'm going to bump the version to 0.8.0 for this. I will also make the `AllocRef` implementation optional behind a cargo feature to avoid future breakage for users that just need `LockedHeap`.

**Comment by phil-opp** [comment]
Released together with #27 as v0.8.0.
